### ISSUE TITLE
How to use transposcope align?

### ISSUE THREAD

**Issue by XinyuXiang** [FenyoLab/transposcope#28]
Dear author, 

Your realignment and visualization tool TranspoScope is very interesting and helpful to my research. I'm trying to do realignment by using **transposcope align** function but a little bit confused about the usage (I want to make the alignment & count on TE more accurate). I mainly have three questions. 

First, could you please give more information about "**index** (the coordinates of insertion sites)" and "**me_reference**(mobile element's FASTA file)"? I did not know which kind of file should be inputted. Since I did not find detailed instruction on your github, an example of **index/me_reference** as well as **a test file** would be great! 

Second, under which condition should I use the parameters "**genes**" and "**group1/group2**"? If I want to get more accurate TE alignment result, should I use them?

Last, which computational tool should I choose, "**melt**" or "**tipseqhunter**"? I do not use TIPseq data (my inputs are RNA-seq, ChIP-seq, ATAC-seq data), so should I use "**melt**"?

Here's the usage I got from "transposcope align -h".
`
usage: TranspoScope align [-h] [--genes GENES] [--group1 GROUP1]
                          [--group2 GROUP2] [--keep_files]
                          {melt,tipseqhunter} index bam me_reference
                          host_reference sample_id

positional arguments:
  {melt,tipseqhunter}  The software used to identify insertions
  index                The path to the index file which describes the
                       coordinates of insertion sites
  bam                  path to bam file
  me_reference         path to the mobile element's FASTA file
  host_reference       path to a folder containing all of the chromosome FASTA
                       files for the host genome
  sample_id            Unique name to for the given experiment. This is used
                       to label the output.

optional arguments:
  -h, --help           show this help message and exit
  --genes GENES        Path to refFlat.txt (If information regarding the
                       nearest gene should be included.)
  --group1 GROUP1      First level group tag (default: ungrouped)
  --group2 GROUP2      Second level group tag (default: ungrouped)
  --keep_files         Flag which determines whether intermediate bam files
                       and fasta files are deleted (default: False)
`

Looking forward to your reply. Thank you very much!

Best,
Xinyu

**Comment by MarkGrivainis** [comment]
Dear Xinyu,

Thank you for your interest in TranspoScope.

Did you read through the wiki page? (https://github.com/FenyoLab/transposcope/wiki)
I have more detailed descriptions listed there as well as some examples.

At this point, TranspoScope can process MELT output which is generated from whole-genome sequencing data. It can also process TIPseqHunter output, which is generated from TIPseq data.

I have not tried to use RNA-seq, ChIP-seq, or ATAC-seq data, and I am unsure whether this type of data can be visualized in the same way that whole-genome sequencing and TIPseq data can.

Best,
Mark

**Comment by XinyuXiang** [comment]
Dear Mark,

Thank you for your quick and detailed response!

I've found the detailed descriptions and examples. I'm sorry I didn't find it first time. It's on the side of the document and my browser didn't show it completely.

TranspoScope is a cool tool. I look forward to you developing more interesting softwares!

I wish you all the best in your research.

Best,
Xinyu
